footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: anymal_b/fake
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 8.5
raytrace_range: 10.0

obstacles_laser:
  observation_sources: point_cloud_sensor
  point_cloud_sensor: {
    data_type: PointCloud2,
    clearing: true,
    marking: true,
    topic: /anymal_b/points_filtered
  }

inflation:
  inflation_radius: 1.0
